In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import re
from html import unescape, escape
from nltk.corpus import stopwords
import nltk
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
stemmer = StemmerFactory().create_stemmer()
stopwords = StopWordRemoverFactory().create_stop_word_remover()
import unicodedata
from nltk.tokenize import word_tokenize
import pickle
import string
from collections import Counter
from tqdm import tqdm

In [4]:
df = pd.read_csv('../dataset/top10cat_balanced.tsv',sep='\t')
df.head()

,product_brand,product_category,product_id,product_name,product_type,review_date,review_id,review_packaging,review_rating,review_rebuy,review_text,review_valueformoney,user_age,user_id,review_text_length
0,Lime Crime,Lipstick,1001.0,Velvetines,Salem,"1,44006E+12",6598,3.0,4,yes,ini the best banget! warna nya bagus suka bang...,expensive,23,8984,223
1,Lime Crime,Lipstick,1001.0,Velvetines,Salem,"1,42728E+12",4149,3.0,3,maybe,aku pakai lime crime seri ini karena pas nikah...,just right,29,35053,238
2,Lime Crime,Lipstick,1001.0,Velvetines,Salem,"1,42851E+12",4243,4.0,5,yes,jatuh cinta sama lime crime ... kalau suedeber...,expensive,34,3340,263
3,Lime Crime,Lipstick,1001.0,Velvetines,Salem,"1,42832E+12",4223,4.0,4,yes,sungguh gak rugi beli ini! warnanya cakep bang...,just right,35,17739,235
4,Lime Crime,Lipstick,1001.0,Velvetines,Salem,"1,41814E+12",3216,5.0,5,yes,pertama kali tau lime crime produk pengen bang...,just right,34,4713,358

In [5]:
singk = pd.read_csv('../dataset/kumpulan_singkatan_dan_kata_dasar.csv',sep=';',header=None)
singk.columns = ['singkatan','kata_dasar']
singk

    singkatan kata_dasar
0        sblm    sebelum
1         pst      pasti
2          dg     dengan
3         nnt      nanti
4           g      tidak
..        ...        ...
214       klo      kalau
215        aq        aku
216         q        aku
217       uda       udah
218       utk      untuk

[219 rows x 2 columns]

In [6]:
def stemming(text):
    return stemmer.stem(text)

def remove_link(text):
    return re.sub(r'http\S+', '', text)

def make_unicode(input):
    if type(input) != unicode:
        input =  input.decode('utf-8')
    return input

def normalizee(text):
    i = 0
    j = 0
    while True:
        match = ''
        if text[i+1] == text[i]:
            j = i
            match = text[j]
            while j <= len(text)-2:
                if text[j+1] == text[j]:
                    match += text[j]
                    j+=1
                else:
                    break
            if len(match) > 2:
                text = text.replace(match,text[i])
        if i+1 <= len(text)-2:
            i+=1
        else:
            break
    return text

not_allowed_char = ['\uf04c','\u200d','\xa0','<br>','&nbsp;','.']
def filter_char(line):
    for denied in not_allowed_char:
        line = line.replace(denied,' ')
    return line

def remove_stopwords(line):
    return stopwords.remove(line)

def to_formal(line):
    for word in word_tokenize(line):
        if word in singk['singkatan'].values.tolist(): 
            idx = singk['singkatan'].values.tolist().index(word)
#             print(idx)
            line = line.replace(word,str(singk.iloc[idx]['kata_dasar']))
    return line

In [7]:
normalizee('awal denger harga segitu lumayan kaget sih tapi ternyata dapet sama refill nya juga, ya oke bangetttt...nyobain make ini juga karena rekomendasi dari colleague dan akhirnya saya merekomendasikan ke saudara saya juga.teksturnya yang ringan membuat serasa gak pake makeup. sebenernya kalo pake ini saja mungkin uda cukup tanpa bedak tapi karena masih belum pd tanpa bedak so abis pake ini, saya masih tetap mengaplikasikan bedak tapi tipis aja.recommended banget nih!!')

'awal denger harga segitu lumayan kaget sih tapi ternyata dapet sama refill nya juga, ya oke banget.nyobain make ini juga karena rekomendasi dari colleague dan akhirnya saya merekomendasikan ke saudara saya juga.teksturnya yang ringan membuat serasa gak pake makeup. sebenernya kalo pake ini saja mungkin uda cukup tanpa bedak tapi karena masih belum pd tanpa bedak so abis pake ini, saya masih tetap mengaplikasikan bedak tapi tipis aja.recommended banget nih!!'

In [1]:
def cleaning_text(text):
    vocab = []
    new_text = []
    for line in tqdm(text,total=len(text)):
        before = len(line)
        new_line = line
        new_line = remove_link(new_line)
        new_line = filter_char(new_line)
        new_line = unescape(new_line)
        new_line = new_line.replace('\\\\\\\\/','/').replace('<br />',' ')
#         new_line = new_line.encode().decode('unicode_escape')
        new_line = unicodedata.normalize("NFKD", new_line)
        new_line = new_line.translate(str.maketrans(' ', ' ', string.punctuation))
        new_line = normalizee(new_line)
        new_line = remove_stopwords(new_line)
        new_line = filter_char(new_line)
        new_line = to_formal(new_line)
#         new_line = stemming(new_line)
        after = len(new_line)
        new_text.append(' '.join(new_line.strip().split()))
        vocab+=word_tokenize(new_line)
    return vocab, new_text

In [30]:
vocab, df['review_text_clean'] = cleaning_text(df.review_text)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 15000/15000 [00:20<00:00, 741.00it/s]

In [33]:
df.to_csv('../dataset/top10cat_balanced_Clean.tsv',index=False,encoding='utf-8')